### ISSUE TITLE
Dynamic Color not work 

### ISSUE THREAD

**Issue by Alotuna** [TanTai97o/Sketchware-Pro#2]
**Describe the bug**

Dynamic Color not work 

**To Reproduce**
1. Step 1 Click settings
2. Step 2 turn on dynamic Color 
3. Step 3 restart app
Sketchware Pro 
v7.0.0-SNAPSHOT-129175c-minApi26

**Comment by TanTai97o** [comment]
This feature is not complete.

**Comment by TanTai97o** [comment]
fixed in https://github.com/TanTai97o/Sketchware-Pro/commit/0cdc49d9196d0a0a418e76491d6f4d00b0e636d0
